### ISSUE TITLE
help with configure

### ISSUE THREAD

**Issue by ArnHD** [BenDol/RocketLauncher#7]
Hello, could you help me with this Launcher?

**Comment by BenDol** [comment]
Hello @ArnHD I have created a quick getting started wiki page to help with how to configure the client and server side https://github.com/BenDol/RocketLauncher/wiki/Getting-Started let me know if you have any questions and I can answer when I have some free time

**Comment by ArnHD** [comment]
Thank you very much boss, maybe will be easier. Do you have a discord?

pon., 27 sty 2020, 15:38 użytkownik Ben Dol <notifications@github.com>
napisał:

**Comment by BenDol** [comment]
Let's keep any set up discussion here for now

**Comment by ArnHD** [comment]
look at this movie please and tell me why :(
https://youtu.be/27DC-Zts42E

pon., 27 sty 2020 o 15:43 Ben Dol <notifications@github.com> napisał(a):

**Comment by BenDol** [comment]
is client.zip the font you want for the launcher? Because you have added it to the `<Font` tag. I assume that is suppose to be the client for the update file?

If that is the case you need to add it to the 0.1-update.xml

You need to go through the [Getting Started](https://github.com/BenDol/RocketLauncher/wiki/Getting-Started) page to make sure you are covering all steps (specifically https://github.com/BenDol/RocketLauncher/wiki/Getting-Started#updates-versionxml-eg-01xml)

**Comment by ArnHD** [comment]
Ok, so I configure your launcher bigining step by step with your tutorial.
Tell me in <font must be moltor moltor.zip etc?

pon., 27 sty 2020, 17:37 użytkownik Ben Dol <notifications@github.com>
napisał:

**Comment by BenDol** [comment]
You can make that any font that you want or remove it to use default font, that is simply an example. You just need to make sure the moltor.zip is on the server and it will install that font for you.

**Comment by ArnHD** [comment]
Ok i undrstand, i will from beginning. We will be in touch hehe.
Best regards.

pon., 27 sty 2020, 18:04 użytkownik Ben Dol <notifications@github.com>
napisał:

**Comment by ArnHD** [comment]
sorry, but I have really problem I think that i do everything good but...

what I doing wrong?
[image: 0.1-update.xml.png]
[image: client folder.png]
[image: launcher.exe.png]
[image: launcher.exe.txt.png]
[image: update.xml.png]
[image: vps files.png]

pon., 27 sty 2020 o 18:30 Bleach Legends <arn.bleachlegend@gmail.com>
napisał(a):

**Comment by ArnHD** [comment]
I would like it to work like a video.
https://www.youtube.com/watch?v=ZJ_F2RZjUjY

pon., 27 sty 2020 o 20:15 Bleach Legends <arn.bleachlegend@gmail.com>
napisał(a):

**Comment by ArnHD** [comment]
Hi, do you read email?

pon., 27 sty 2020, 20:18 użytkownik Bleach Legends <
arn.bleachlegend@gmail.com> napisał:

**Comment by BenDol** [comment]
I cant see any of the screenshots you shared

**Comment by ArnHD** [comment]
wt., 28 sty 2020, 19:07 użytkownik Ben Dol <notifications@github.com>
napisał:

**Comment by ArnHD** [comment]
Did you get now?

wt., 28 sty 2020, 20:34 użytkownik Bleach Legends <
arn.bleachlegend@gmail.com> napisał:

**Comment by BenDol** [comment]
no

**Comment by ArnHD** [comment]
Do you have a messenger or discord?

wt., 28 sty 2020, 20:48 użytkownik Ben Dol <notifications@github.com>
napisał:

**Comment by ArnHD** [comment]
Why closed?

wt., 28 sty 2020, 20:50 użytkownik Ben Dol <notifications@github.com>
napisał:

**Comment by ArnHD** [comment]
https://www84.zippyshare.com/v/jyyPJ6Ha/file.html

look here are photos.

**Comment by BenDol** [comment]
Make sure you are using https://github.com/BenDol/RocketLauncher/releases/tag/v1.0-rc2

Can you share the `layout.xml` code here?

**Comment by ArnHD** [comment]
sure. this is my layout.xml
`<?xml version="1.0" encoding="utf-8" ?>
<Layout>
  <Launcher.Interface.ControlLabel name="lblName">
    <Accessibility>
      <AccessibleName></AccessibleName>
      <AccessibleDescription></AccessibleDescription>
      <AccessibleRole>Default</AccessibleRole>
    </Accessibility>
    <Appearance>
      <Text>Bleach Legends Launcher</Text>
      <BackColor>Control</BackColor>
      <CompositeQuality>HighQuality</CompositeQuality>
      <Cursor>Default</Cursor>
      <DisabledTextColor>SteelBlue</DisabledTextColor>
      <FlatStyle>Standard</FlatStyle>
      <ForeColor>SteelBlue</ForeColor>
      <Image></Image>
      <ImageIndex></ImageIndex>
      <ImageKey></ImageKey>
      <ImageList></ImageList>
      <ImageAlign>MiddleCenter</ImageAlign>
      <RightToLeft>No</RightToLeft>
      <SmoothingMode>HighQuality</SmoothingMode>
      <TextAlign>TopLeft</TextAlign>
      <TextRenderHint>AntiAliasGridFit</TextRenderHint>
      <UseMnmonic>True</UseMnmonic>
      <UseWaitCursor>False</UseWaitCursor>
    </Appearance>
    <Behavior>
      <AllowDrop>False</AllowDrop>
      <AutoEllipsis>True</AutoEllipsis>
      <Enabled>False</Enabled>
      <TabIndex>11</TabIndex>
      <UseCompatibleTextRendering>False</UseCompatibleTextRendering>
      <Visible>True</Visible>
    </Behavior>
    <Design>
      <GenerateMember>True</GenerateMember>
      <Locked>False</Locked>
      <Modifiers>Private</Modifiers>
    </Design>
    <Focus>
      <CausesValidation>True</CausesValidation>
    </Focus>
    <Layout>
      <Anchor>Top, Left</Anchor>
      <AutoSize>True</AutoSize>
      <Dock>None</Dock>
      <Location X="5" Y="7"/>
      <Margin All="-1" Left="3" Top="0" Right="3" Bottom="0"/>
      <Padding All="0" Left="0" Top="0" Right="0" Bottom="0"/>
      <MaximumSize Width="0" Height="0"/>
      <MinimumSize Width="0" Height="0"/>
      <Size Width="150" Height="33"/>
    </Layout>
  </Launcher.Interface.ControlLabel>

  <Launcher.Interface.GlossyButton name="btnLaunch">
    <Accessibility>
      <AccessibleName></AccessibleName>
      <AccessibleDescription></AccessibleDescription>
      <AccessibleRole>Default</AccessibleRole>
    </Accessibility>
    <Appearance>
      <Text>Start</Text>
      <Font size="8.25" unit="Point" bold="false" italic="false" strikeout="false" underline="false" gdicharset="0" gdiverticalfont="false">Tahoma</Font>
      <ActiveBackColor>DarkSeaGreen</ActiveBackColor>
      <ActiveBorderColor>White</ActiveBorderColor>
      <BackColor>Control</BackColor>
      <BackgroundImage></BackgroundImage>
      <BackgroundImageLayout>Tile</BackgroundImageLayout>
      <BorderColor>White</BorderColor>
      <Cursor>Default</Cursor>
      <DisabledTextColor>SteelBlue</DisabledTextColor>
      <FlatStyle>Standard</FlatStyle>
      <ForeColor>SteelBlue</ForeColor>
      <HoverBackColor>MediumAquamarine</HoverBackColor>
      <HoverBorderColor>White</HoverBorderColor>
      <RightToLeft>No</RightToLeft>
      <StandbyBackColor>DarkSeaGreen</StandbyBackColor>
      <StandbyBorderColor>White</StandbyBorderColor>
      <UseWaitCursor>False</UseWaitCursor>
    </Appearance>
    <Behavior>
      <AllowDrop>False</AllowDrop>
      <AutoValidate>True</AutoValidate>
      <Enabled>False</Enabled>
      <ImeMode>NoControl</ImeMode>
      <TabIndex>6</TabIndex>
      <TabStop>True</TabStop>
      <Visible>True</Visible>
    </Behavior>
    <Design>
      <GenerateMember>True</GenerateMember>
      <Locked>False</Locked>
      <Modifiers>Private</Modifiers>
    </Design>
    <Focus>
      <CausesValidation>True</CausesValidation>
    </Focus>
    <Layout>
      <Anchor>Top, Left</Anchor>
      <AutoScroll>False</AutoScroll>
      <AutoScrollMargin Width="0" Height="0"/>
      <AutoScrollMinSize Width="0" Height="0"/>
      <AutoSize>True</AutoSize>
      <AutoSizeMode>GrowOnly</AutoSizeMode>
      <Dock>None</Dock>
      <Location X="427" Y="309"/>
      <Margin All="3" Left="3" Top="3" Right="3" Bottom="3"/>
      <Padding All="0" Left="0" Top="0" Right="0" Bottom="0"/>
      <MaximumSize Width="0" Height="0"/>
      <MinimumSize Width="0" Height="0"/>
      <Size Width="76" Height="39"/>
    </Layout>
  </Launcher.Interface.GlossyButton>
</Layout>`

**Comment by BenDol** [comment]
Please fix the formatting using markdown ` ```xml`

**Comment by ArnHD** [comment]
https://pastebin.com/a7fTsJRD

**Comment by ArnHD** [comment]
maybe my software is wrong...

**Comment by ArnHD** [comment]
I used RocketLauncher.exe and files from v.1.2 on vps i make files, banner.png, data.zip and this second png so i start application i have the same error and app i closed.

**Comment by ArnHD** [comment]
I think that layout.xml is wrong becouse launcher dont want download/read this file.

**Comment by ArnHD** [comment]
Maybe you configure this launcher on your pc i give you information what you need.

**Comment by ArnHD** [comment]
Hi, are you there?
